export interface Liga1 {
    rank: string,
    team: string,
    teamId: string,
    form: string,
    team_form: string,
    played: string,
    win: string,
    draw: string,
    lost: string,
    for: string,
    against: string,
    diff: string,
    points: string,
    st: string,
    group: string,
    conference: string,
    logos: {},
    notes: string,
    leagueId: string,
    seasons: [],
    hasLineupInfo: boolean,
    leagueName: string
}